const patients = {
  losData: [
    {
      "ID": 231677,
      "LOS": 25.529166666666665,
      "blood": 0,
      "circulatory": 0,
      "congenital": 0,
      "digestive": 0,
      "endocrine": 0,
      "genitourinary": 0,
      "infectious": 0,
      "injury": 0,
      "mental": 0,
      "misc": 0,
      "muscular": 0,
      "neoplasms": 1,
      "nervous": 0,
      "pregnancy": 0,
      "prenatal": 0,
      "respiratory": 0,
      "skin": 0,
      "GENDER": 1,
      "ICU": 1,
      "NICU": 0,
      "ADM_ELECTIVE": 0,
      "ADM_EMERGENCY": 1,
      "ADM_NEWBORN": 0,
      "ADM_URGENT": 0,
      "INS_Government": 0,
      "INS_Medicaid": 0,
      "INS_Medicare": 0,
      "INS_Private": 1,
      "INS_Self Pay": 0,
      "REL_NOT SPECIFIED": 0,
      "REL_RELIGIOUS": 1,
      "REL_UNOBTAINABLE": 0,
      "ETH_ASIAN": 0,
      "ETH_BLACK/AFRICAN AMERICAN": 0,
      "ETH_HISPANIC/LATINO": 0,
      "ETH_OTHER/UNKNOWN": 0,
      "ETH_WHITE": 1,
      "AGE_300": 0,
      "AGE_middle_adult": 1,
      "AGE_newborn": 0,
      "AGE_senior": 0,
      "AGE_young_adult": 0,
      "MAR_DIVORCED": 0,
      "MAR_LIFE PARTNER": 0,
      "MAR_MARRIED": 1,
      "MAR_SEPARATED": 0,
      "MAR_SINGLE": 0,
      "MAR_UNKNOWN (DEFAULT)": 0,
      "MAR_WIDOWED": 0,
    },
    {
      "ID": 231678,
      "LOS": 3.1486111111111112,
      "blood": 0,
      "circulatory": 0,
      "congenital": 1,
      "digestive": 0,
      "endocrine": 0,
      "genitourinary": 0,
      "infectious": 0,
      "injury": 0,
      "mental": 0,
      "misc": 0,
      "muscular": 0,
      "neoplasms": 0,
      "nervous": 0,
      "pregnancy": 0,
      "prenatal": 0,
      "respiratory": 0,
      "skin": 0,
      "GENDER": 0,
      "ICU": 1,
      "NICU": 0,
      "ADM_ELECTIVE": 0,
      "ADM_EMERGENCY": 1,
      "ADM_NEWBORN": 0,
      "ADM_URGENT": 0,
      "INS_Government": 0,
      "INS_Medicaid": 0,
      "INS_Medicare": 0,
      "INS_Private": 1,
      "INS_Self Pay": 0,
      "REL_NOT SPECIFIED": 0,
      "REL_RELIGIOUS": 1,
      "REL_UNOBTAINABLE": 0,
      "ETH_ASIAN": 0,
      "ETH_BLACK/AFRICAN AMERICAN": 0,
      "ETH_HISPANIC/LATINO": 0,
      "ETH_OTHER/UNKNOWN": 0,
      "ETH_WHITE": 1,
      "AGE_300": 0,
      "AGE_middle_adult": 1,
      "AGE_newborn": 0,
      "AGE_senior": 0,
      "AGE_young_adult": 0,
      "MAR_DIVORCED": 0,
      "MAR_LIFE PARTNER": 0,
      "MAR_MARRIED": 1,
      "MAR_SEPARATED": 0,
      "MAR_SINGLE": 0,
      "MAR_UNKNOWN (DEFAULT)": 0,
      "MAR_WIDOWED": 0,
    },
    {
      "ID": 231679,
      "LOS": 7.989583333333333,
      "blood": 0,
      "circulatory": 1,
      "congenital": 0,
      "digestive": 0,
      "endocrine": 0,
      "genitourinary": 0,
      "infectious": 0,
      "injury": 0,
      "mental": 0,
      "misc": 0,
      "muscular": 0,
      "neoplasms": 0,
      "nervous": 0,
      "pregnancy": 0,
      "prenatal": 0,
      "respiratory": 0,
      "skin": 0,
      "GENDER": 0,
      "ICU": 1,
      "NICU": 0,
      "ADM_ELECTIVE": 1,
      "ADM_EMERGENCY": 0,
      "ADM_NEWBORN": 0,
      "ADM_URGENT": 0,
      "INS_Government": 0,
      "INS_Medicaid": 0,
      "INS_Medicare": 0,
      "INS_Private": 1,
      "INS_Self Pay": 0,
      "REL_NOT SPECIFIED": 0,
      "REL_RELIGIOUS": 1,
      "REL_UNOBTAINABLE": 0,
      "ETH_ASIAN": 0,
      "ETH_BLACK/AFRICAN AMERICAN": 0,
      "ETH_HISPANIC/LATINO": 0,
      "ETH_OTHER/UNKNOWN": 1,
      "ETH_WHITE": 0,
      "AGE_300": 0,
      "AGE_middle_adult": 0,
      "AGE_newborn": 0,
      "AGE_senior": 0,
      "AGE_young_adult": 1,
      "MAR_DIVORCED": 0,
      "MAR_LIFE PARTNER": 0,
      "MAR_MARRIED": 1,
      "MAR_SEPARATED": 0,
      "MAR_SINGLE": 0,
      "MAR_UNKNOWN (DEFAULT)": 0,
      "MAR_WIDOWED": 0,
    }
  ]
}

export default patients